# Generated by Django 4.1.3 on 2022-11-28 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snowdays23', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, verbose_name='unique alphanumerical string identifying order')),
                ('status', models.CharField(choices=[('pending', 'Non pagato'), ('paid', 'Pagato')], default='pending', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time of this order')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='total amount of this order')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowdays23.participant', verbose_name='participant that placed this order')),
            ],
        ),
    ]
