# Generated by Django 4.1.3 on 2022-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd23payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='pp_capture',
            field=models.JSONField(blank=True, null=True, verbose_name='payment details provided by paypal after checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='pp_order_id',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='paypal order id assigned during checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='sd_order_id',
            field=models.CharField(default=None, max_length=32, verbose_name='unique alphanumerical string identifying order internally'),
            preserve_default=False,
        ),
    ]
