# Generated by Django 4.1.3 on 2022-12-10 17:09

from django.db import migrations, models
import sd23payments.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sd23payments', '0002_remove_order_order_id_order_pp_capture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='display name of item')),
                ('slug', models.CharField(max_length=16, verbose_name='id of item')),
                ('price', models.IntegerField(verbose_name='unit price of item in cents')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pp_capture',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pp_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_order_id',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='stripe order id assigned during checkout'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sd_order_id',
            field=models.CharField(default=sd23payments.utils.generate_sd_order_id, max_length=32, verbose_name='unique alphanumerical string identifying order internally'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Not paid'), ('paid', 'Paid')], default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='sd23payments.billableitem', verbose_name='items included in this order'),
        ),
    ]
