# Generated by Django 4.1.3 on 2023-01-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd23payments', '0003_billableitem_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_order_id',
            field=models.CharField(blank=True, max_length=92, null=True, verbose_name='stripe order id assigned during checkout'),
        ),
    ]
