# Generated by Django 4.1.3 on 2023-02-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0013_partybeast'),
        ('sd23payments', '0004_alter_order_stripe_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='party_beast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowdays23.partybeast', verbose_name='party beast that placed this order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowdays23.participant', verbose_name='participant that placed this order'),
        ),
    ]
