# Generated by Django 4.1.3 on 2022-12-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='day',
        ),
    ]
