# Generated by Django 4.1.3 on 2022-12-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0002_remove_gear_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.BooleanField(default=False, verbose_name='has read and accepted privacy policy')),
                ('terms', models.BooleanField(default=False, verbose_name='has read and accepted terms and conditions')),
                ('payment', models.BooleanField(default=False, verbose_name='has read and accepted payment policy')),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='helmet_size',
            field=models.CharField(blank=True, choices=[('XS', 'extra small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], max_length=2, null=True, verbose_name='head size'),
        ),
        migrations.AlterField(
            model_name='university',
            name='email_domain',
            field=models.TextField(blank=True, null=True, verbose_name='domain name associated with this university'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('university', 'student_nr')},
        ),
        migrations.AddField(
            model_name='participant',
            name='policies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snowdays23.policies', verbose_name='status of sign-up policies'),
        ),
    ]
