# Generated by Django 4.1.3 on 2023-01-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0003_policies_alter_participant_helmet_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(verbose_name='pre-registered email provided by guest uni')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='street name')),
                ('street_nr', models.CharField(max_length=6, verbose_name='street number')),
                ('is_college', models.BooleanField(default=False, verbose_name='location is a college')),
                ('college_slug', models.CharField(blank=True, max_length=32, null=True, verbose_name='college id')),
                ('college_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='college full name')),
                ('max_guests', models.IntegerField(default=-1, verbose_name='maximum number of guests this location can hold at once')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='room_nr',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='host college room number'),
        ),
        migrations.AddField(
            model_name='participant',
            name='selected_sport',
            field=models.CharField(choices=[('ski', 'Skii'), ('snowboard', 'Snowboard'), ('none', 'None')], default='none', max_length=16, verbose_name='selected sport during sign-up'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(choices=[('ski', 'Skii'), ('snowboard', 'Snowboard'), ('helmet', 'Helmet'), ('poles', 'Skii Poles'), ('skiboots', 'Skii Boots'), ('snowboardboots', 'Snowboard Boots')], default='ski', max_length=16, verbose_name='name of rented gear'),
        ),
        migrations.AddField(
            model_name='participant',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snowdays23.residence', verbose_name='host location'),
        ),
    ]
