# Generated by Django 4.1.3 on 2023-01-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0004_allowedparticipant_residence_participant_room_nr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalUserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('full', 'Full Price'), ('helper', 'Helper'), ('host', 'Host'), ('host+helper', 'Host and Helper')], max_length=16, verbose_name='user type')),
                ('guests', models.IntegerField(default=0, verbose_name='external guests hosted')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='internal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snowdays23.internalusertype', verbose_name='internal user type'),
        ),
    ]
