# Generated by Django 4.1.3 on 2023-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0005_internalusertype_participant_internal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='city',
            field=models.CharField(default='Bolzano', max_length=32, verbose_name='city or town'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residence',
            name='postal_code',
            field=models.CharField(default='39100', max_length=8, verbose_name='postal code'),
            preserve_default=False,
        ),
    ]
