# Generated by Django 4.1.3 on 2023-01-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0007_alter_residence_max_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalusertype',
            name='name',
            field=models.CharField(choices=[('full', 'Full Price'), ('helper', 'Helper'), ('host', 'Host'), ('host+helper', 'Host and Helper'), ('alumnus', 'Alumnus')], max_length=16, verbose_name='user type'),
        ),
    ]
