# Generated by Django 4.1.3 on 2023-01-14 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0008_alter_internalusertype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedAlumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(verbose_name='pre-registered email provided by unibz')),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='internal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowdays23.internalusertype', verbose_name='internal user type'),
        ),
    ]
