# Generated by Django 4.1.3 on 2023-01-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0009_allowedalumnus_alter_participant_internal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedalumnus',
            options={'verbose_name_plural': 'Allowed alumni'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='internal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='snowdays23.internalusertype', verbose_name='internal user type'),
        ),
    ]
