# Generated by Django 4.1.3 on 2023-01-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0010_alter_allowedalumnus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='internal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snowdays23.internalusertype', verbose_name='internal user type'),
        ),
    ]
