# Generated by Django 4.1.3 on 2023-01-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0011_alter_participant_internal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='eating_habits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snowdays23.eatinghabits', verbose_name='special eating needs declared by this participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snowdays23.residence', verbose_name='host location'),
        ),
    ]
