# Generated by Django 4.1.3 on 2023-02-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0013_partybeast'),
    ]

    operations = [
        migrations.AddField(
            model_name='partybeast',
            name='policies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='snowdays23.policies', verbose_name='status of sign-up policies'),
        ),
    ]
