# Generated by Django 4.1.3 on 2023-02-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowdays23', '0014_partybeast_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partybeast',
            name='student_nr',
        ),
    ]
