# Generated by Django 4.1.3 on 2023-02-15 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snowdays23', '0015_remove_partybeast_student_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name of the tracked event')),
                ('slug', models.CharField(max_length=64, verbose_name='short name of the tracked event')),
                ('description', models.TextField(verbose_name='additional info about this event')),
                ('icon', models.CharField(max_length=16, verbose_name='id of the icon resource for this event')),
                ('only_participants', models.BooleanField(default=True, verbose_name='flag indicating whether only participants are allowed to be checked in to this event')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanning_time', models.DateTimeField(auto_now_add=True, verbose_name='time of check-in')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sd23log.event', verbose_name='event to which check-in is performed')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowdays23.participant', verbose_name='checked in participant')),
                ('party_beast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowdays23.partybeast', verbose_name='checked in party beast')),
            ],
        ),
    ]
